language: ruby
rvm:
- 2.0.0
services:
- postgresql
before_script:
  - psql -c 'create database timeclock_development;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Su6CgQkoCPNbco2iJt4cVhGG34awX7ZHZiGT/lKMHNk4WOskh025lBankUq0DMUkf2u95+xOyr2k38vxotLmZxrNMbGRjal5YszUdAyV6yjajHRrB6itMqT3iSf3U8PPTM/B3Yp3tIhHeklhZZX7ar4P6tDk7XCPjD3erIh3HCA2IjMNCdMXxQyS9MgJ+boNuJR3jC/o4CKCI1gL0OHfNzN/AAfNLpFsOcGf7zJUxs8J2LTwVbvo+XIlxj6RIXfF/qOE7TPMxYTxx+fCL3A2v4H2IywoO3CVjivQkSwPkoo9l2Dgd4fDeTuSjlUtkveXwMERRPGrpfCRNyi8+g3L+HYnHtpVAC4iJQ+sIsl3PDekVCX+BP+iPBbIDe7JAud4zjebZUTzh9znyAV4dfnzu6lI3rjL+WNsshvDOJ9G2ifXdYmE8XdCkr5rWZ+8NUVIDNtn7K1itjgRrDO8t5PDe8i0QSEXIdzq7KU5YysjyjbJa3JkurQdt0hwYgOynFuq0hnAab0G7gUjH1UWl31qA8m0bMDDUJr0gg7+om2lI7O1vXjEJfYUqCatMXMEevt7iCnQD+9NZvAIgP+PbzCoaiciycb7BNQ7HdFFh96N8fJc58FhKgat7xVI/ayUfL2yJaFvQhn6HB7/1sHEChIONILxT8XJsNEnN2v9vzKCYa8=
  app: ennovar-timekeeping
